eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
server:
    port: 8762
spring:
    application:
        name: zuul-server
zuul:
    ignored-services: '*'
    routes:
        moni-pte-service:
            path: /monipte/**
            service-id: moni-pte-service
        moni-user-service:
            path: /moniuser/**
            service-id: moni-user-service
